### ISSUE TITLE
Standalone file export

### ISSUE THREAD

**Issue by igordertigor** [twitwi/deck.js-starterkit#1]
I really like this deck.js starterkit. The layout is nice and clean and it is a great way to get started with deck.js. Yet, there is one feature I have been looking for. I might have missed it, but is it possible to export a presentation as a single standalone html file? If so, how would I use that?

**Comment by twitwi** [comment]
There are currently two limitations. But, in case you:
1. do not use the `@svg` and `@chunk` (not illustrated in the starter-kit) 
2. do not use math equations (or are ok with the math fonts to not be embedded)

You can use this tool https://github.com/remy/inliner, following two steps:

- You need to remove all elements from the custom loader to get line 53 as `var cssAndJs = [""]`and use the traditional inclusion mechanisms for CSS and JS, e.g., `<link href="light-red-dense.css" rel="stylesheet">`

- You need to use the `-n` option, with a command like `inliner -n  index.html > standalone.html`

Working around the two limitations would be possible (limitation 2 is easier).

**Comment by twitwi** [comment]
NB: workaround for limitation 2 is confirmed (although the html file is then around 3MB bigger).

**Comment by igordertigor** [comment]
I see. Thank you. `@svg` and math equations are two big plusses for me in using deck.js. I would rather not want to miss them. But I see the problem. I'll try to figure out a workaround.

**Comment by twitwi** [comment]
I experimented and could work around the `@svg` issue. This needed some manual intervention that I will need to translate into “fixes” for my extensions.

The idea is to have a “save” button in the presentation that will export the DOM tree after processing of the `@svg`, `@chunk`, et al. Once this file is saved, (currently after some manual tuning) it can be fed to the existing `inliner` program to embed the rest (images, fonts, etc).

**Comment by igordertigor** [comment]
Cool, I'm looking forward to seeing that. It sounds interesting.

**Comment by twitwi** [comment]
Hi @igordertigor 
 
The standalone export seems to be working, even though it involves calling the inliner manually.

By default it can be started with the `d` key (d like "dump DOM"), then it will tell you to follow a few steps (and will start a download):

> To make a single-file standalone presentation:
> 
>  1) save the download next to your presentation file
>  2) name it for example export.html
>  3) install nodejs and https://github.com/remy/inliner
>  4) invoke the inliner with this command:
>        inliner -n -m export.html > standalone.html
> 
>  ⇒⇒⇒ 'standalone.html' should now contain everything,
>                        you can move it where you want.

Don't hesitate to comment if it works or to reopen the issue if it does not.
Thanks for the motivation boost: by your asking for the feature, I finally crossed an item that has been on a todo list for quite a while :ballot_box_with_check: .

**Comment by twitwi** [comment]
Note: the current version of remy/inliner has issues with url() inside style="", like this

    <div class="img" style="background-image: url(media/iris.jpg)"></div>

I have a fix but it is a partial one so I'm not sure it will get included in the main repo.
https://github.com/remy/inliner/issues/152

**Comment by twitwi** [comment]
Related PR: https://github.com/remy/inliner/pull/154

**Comment by igordertigor** [comment]
Great, I already saw this and will try it out in the next couple of days.
